
version: "3"
services:
  libsysdb:
    image: postgres:latest
    container_name: libsysdb
    volumes:
      - libsys_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=libsysdb
    restart: unless-stopped
    networks:
      - default
  libsysbe:
    image: dzieniu/libsysbe:latest
    container_name: libsysbe
    ports:
      - 8080:8080
    environment:
      - DB_HOST=libsysdb
      - DB_PORT=5432
      - DB_NAME=libsysdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
    restart: unless-stopped
    depends_on:
      - libsysdb
    links:
      - libsysdb
    networks:
      - default
volumes:
  libsys_data:
networks:
  default: